apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-of-ai-solutions
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-of-ai-solutions
  template:
    metadata:
      labels:
        app: deployment-of-ai-solutions
    spec:
      containers:
      - name: deployment-of-ai-solutions
        image: deployment_app:latest
        ports:
        - containerPort: 5000